rely on "provenance statements" when publishing our builds
In the light of recent [npm security news on very popular packages that
have been compromised on the npm registry](https://www.aikido.dev/blog/npm-debug-and-chalk-packages-compromised)
(we're not affected it seems), I thought about how we can improve our
publish pipeline so applications can trust it.

_(This issue began as a fishing email from an npm impersonator,
the change wasn't made on the base repo, it was only published to
the `npm` registry directly from the attacker. What it did was to
redirect cryptocurrencies transactions when in a browser)._

How it works for now
--------------------

When we publish a package on the npm registry, we do so by running
scripts (in the `scripts/` directory) locally, and then call `npm
publish` locally (while being authentified on npm with the right
token).

So applications have to trust that:
  1. what we published was indeed linked to the code present in the
     git repository at that point.
  2. that we ran the same pushed build scripts to publish it,
     without modifying files first (which could be done only locally).

How can we improve on it
------------------------

It seems that npm provides a mechanim called ["provenance
statements"](https://docs.npmjs.com/generating-provenance-statements).

The idea is to rely on a CI as a third party (they support only GitHub
and Gitlab for now) which will do both the build process and the
publishing in its entirety server-side, on a CI script that would be
easy to audit (and the auditable source files that have been pushed) by
another application wanting to rely on us.

Also, the repo linked to that CI has to be the repository listed in the
project's `package.json` (it is for us!).

What I did
----------

I updated our publish scripts so they don't do the build nor publishing
anymore.

Now they only check that conditions are right locally (e.g. the release
has not already been published etc.) and then create a version tag (both
for official and dev releases) and push to the current branch.

On those tags, CI scripts are now scheduled:

- for official releases, it builds the rx-player then publish the result
  on npm

- for dev releases, it does both the `dev` and `canal` releases. It also
  on its side that the "canal patch" is applied. That apply is checked
  multiple times (both locally and by the CI) to be sure it can be
  applied before doing any publishing.

Our build script is still complex (to be easily auditable by an
application), but I think it's a step in the right direction.

There's though still a small detail: the secret token hasn't been added
to GitHub yet (this is needed for the npm token), I'll have to contact
the right people for that and it might take some time!
I also haven't tested this, so no idea if I forgot some key step for
now.

But anyway I still commit this to be able to receive opinions on this.

Also, we did not create tags for dev releases until now, but this means
that we'll do it. I have no problem with it though, I even think that's
a good idea to be able to check more quickly what a particular dev
release contained (we would just checkout the tag).

diff --git a/scripts/make-dev-releases b/scripts/make-dev-releases
--- a/scripts/make-dev-releases
+++ b/scripts/make-dev-releases
@@ -64,8 +64,6 @@ current_branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
 date=$(date "+%Y%m%d")
 dev_version="${version}-dev.${date}${incr}"
 canal_version="${version}-canal.${date}${incr}"
-dev_branch="release/v${dev_version}"
-canal_branch="release/v${canal_version}"
 
 if [ -n "$(git status --porcelain)" ]; then
   err "There is unstaged changes in your worktree. Please commit your changes or stash them before creating the release."
@@ -73,19 +71,12 @@ fi
 
 echo "This script will create the dev versions: $dev_version and $canal_version"
 
-echo "checking that the branches do not already exist locally or remotely..."
-if ! [ -z $(git branch --list "$dev_branch") ]; then
-  err "Branch name \"$dev_branch\" already exists locally. Please delete it first."
+if ! git apply --check ./scripts/canal-release.patch; then
+  echo "Error: Canal patch cannot be applied cleanly!"
+  echo "Please resolve conflicts in the patch file before proceeding."
+  exit 1
 fi
-if ! [ -z $(git branch --list "$canal_branch") ]; then
-  err "Branch name \"$canal_branch\" already exists locally. Please delete it first."
-fi
-if ! [ -z $(git ls-remote --heads git@github.com:canalplus/rx-player.git "refs/heads/$dev_branch") ]; then
-  err "Branch name \"$dev_branch\" already exists remotely. Please delete it first."
-fi
-if ! [ -z $(git ls-remote --heads git@github.com:canalplus/rx-player.git "refs/heads/$canal_branch") ]; then
-  err "Branch name \"$canal_branch\" already exists remotely. Please delete it first."
-fi
+echo "Canal patch check passed ✓"
 
 echo "checking that the versions are not already published on npm..."
 if npm view rx-player@$dev_version >/dev/null 2>&1; then
@@ -150,12 +141,8 @@ if [ -n "$(git status --porcelain)" ]; then
   err "Unexpected diff in \"${current_branch}\""
 fi
 
-git checkout -b ${dev_branch}
-./scripts/update-version $version-dev.${date}${incr}
-git add --all
-git commit -m "update version"
 while true; do
-  read -n1 -p "Do you wish to push and publish the dev build? [y/n] " yn
+  read -n1 -p "Do you wish to publish the dev and canal builds? [y/n] " yn
   echo ""
   case $yn in
   [Yy]*) break ;;
@@ -163,24 +150,7 @@ while true; do
   *) echo "Please answer y or n." ;;
   esac
 done
-git push origin ${dev_branch}
-npm publish --tag dev-v4
 
-git checkout $current_branch
-
-git checkout -b ${canal_branch}
-git apply ./scripts/canal-release.patch
-./scripts/update-version $version-canal.${date}${incr}
-git add --all
-git commit -m "update version"
-git push origin ${canal_branch}
-while true; do
-  read -n1 -p "Do you wish to push and publish the canal build? [y/n] " yn
-  echo ""
-  case $yn in
-  [Yy]*) break ;;
-  [Nn]*) exit ;;
-  *) echo "Please answer y or n." ;;
-  esac
-done
-npm publish --tag canal-v4
+# TODO: Include release note as a tag description?
+git tag -a "v${dev_version}" -m "RxPlayer dev release: v${dev_version}"
+git push origin ${current_branch}
