wip

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -148,21 +148,48 @@ jobs:
       - run: |
           npm ci
           npm run build
-          for browser in "chrome" "firefox" "edge"; do
-            npm run test:integration:$browser
-            # retry on failure
-            if [ $? -ne 0 ]; then
-              echo "First tests attempt failed. Retrying after 20 seconds..."
-              sleep 20
-              npm run test:integration:$browser
-            fi
-            # Other OSes than linux are particularly bad on github actions, run it three times
-            if [ $? -ne 0 ]; then
-              echo "Second tests attempt failed. Retrying after 60 seconds..."
-              sleep 60
-              npm run test:integration:$browser
-            fi
-          done
+          # TODO: I tried doing a for loop but I'm so bad in bash I couldn't make
+          # `$?` work with string interpolation. So let's unroll that loop
+          # instead.
+          npm run test:integration:chrome
+          # retry on failure
+          if [ $? -ne 0 ]; then
+            echo "First chrome tests attempt failed. Retrying after 20 seconds..."
+            sleep 20
+            npm run test:integration:chrome
+          fi
+          # Other OSes than linux are particularly bad on github actions, run it three times
+          if [ $? -ne 0 ]; then
+            echo "Second chrome tests attempt failed. Retrying after 60 seconds..."
+            sleep 60
+            npm run test:integration:chrome
+          fi
+          npm run test:integration:firefox
+          # retry on failure
+          if [ $? -ne 0 ]; then
+            echo "First firefox tests attempt failed. Retrying after 20 seconds..."
+            sleep 20
+            npm run test:integration:firefox
+          fi
+          # Other OSes than linux are particularly bad on github actions, run it three times
+          if [ $? -ne 0 ]; then
+            echo "Second firefox tests attempt failed. Retrying after 60 seconds..."
+            sleep 60
+            npm run test:integration:firefox
+          fi
+          npm run test:integration:edge
+          # retry on failure
+          if [ $? -ne 0 ]; then
+            echo "First edge tests attempt failed. Retrying after 20 seconds..."
+            sleep 20
+            npm run test:integration:edge
+          fi
+          # Other OSes than linux are particularly bad on github actions, run it three times
+          if [ $? -ne 0 ]; then
+            echo "Second edge tests attempt failed. Retrying after 60 seconds..."
+            sleep 60
+            npm run test:integration:edge
+          fi
 
   memory_linux:
     runs-on: ubuntu-latest
