CI: each browser three times on macos

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -148,19 +148,21 @@ jobs:
       - run: |
           npm ci
           npm run build
-          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
-          # retry on failure
-          if [ $? -ne 0 ]; then
-            echo "First tests attempt failed. Retrying after 20 seconds..."
-            sleep 20
-            npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
-          fi
-          # Other OSes than linux are particularly bad on github actions, run it three times
-          if [ $? -ne 0 ]; then
-            echo "Second tests attempt failed. Retrying after 60 seconds..."
-            sleep 60
-            npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
-          fi
+          for browser in "chrome" "firefox" "edge"; do
+            npm run "test:integration:$browser"
+            # retry on failure
+            if [ $? -ne 0 ]; then:
+              echo "First tests attempt failed. Retrying after 20 seconds..."
+              sleep 20
+              npm run "test:integration:$browser"
+            fi
+            # Other OSes than linux are particularly bad on github actions, run it three times
+            if [ $? -ne 0 ]; then
+              echo "Second tests attempt failed. Retrying after 60 seconds..."
+              sleep 60
+              npm run "test:integration:$browser"
+            fi |
+          done
 
   memory_linux:
     runs-on: ubuntu-latest
